#inline comments are forbidden
#write comments on different lines with config code

--- !org.egslava.ftp.config.Config
hostName: localhost
portNumber: 2121
debugOutput: true
portRanges: !org.egslava.ftp.config.PortRange[]
 - !org.egslava.ftp.config.PortRange
     from: 1025
     to:   1225
 - !org.egslava.ftp.config.PortRange
     from: 2048
     to  : 3098

#Anonymous users only mode. if true - you can't login under your login.
anonymousOnly: true 
users: !org.egslava.ftp.config.User[]
 - !org.egslava.ftp.config.User
     login: egslava
     password: egslava
     home: ./ftp/egslava

#================= to do ========================
#access:
#anonymous only / authenticated only / both
#anonymous can upload / anonymous can create directories

#performance
#Max iddle time
#Max clients for one IP
#Max clients
#local max rate (kb/s)
#anonymous max rate
