#inline comments are forbidden
#write comments on different lines with config code

--- !org.egslava.ftp.Config
hostName: localhost
portNumber: 2121
debugOutput: true

#Anonymous users only mode. if true - you can't login under your login.
anonymousOnly: true 
